FROM ollama/ollama:0.6.5

SHELL ["/bin/bash", "-c"]

RUN apt-get update && apt-get install -y \
    python3 \
    python3-pip \
    git \
    build-essential \
    apt-utils \
    && ln -s /usr/bin/python3 /usr/bin/python \
    && rm -rf /var/lib/apt/lists/*

# Python 패키지 설치
RUN pip install ollama tqdm

# 작업 디렉토리 설정
WORKDIR /app
