FROM ollama/ollama:0.6.5

SHELL ["/bin/bash", "-c"]

RUN apt-get update && apt-get install -y \
    python3 \
    python3-pip \
    git \
    build-essential \
    apt-utils \
    && ln -s /usr/bin/python3 /usr/bin/python \
    && rm -rf /var/lib/apt/lists/*

# Python 패키지 설치
RUN pip install ollama

# 작업 디렉토리 설정
WORKDIR /app

# Ollama 서비스가 사용하는 포트 노출
EXPOSE 11434

# Ollama 서비스 시작 (필요한 경우)
# CMD ["ollama", "serve"]
